apiVersion: v1
kind: Service
metadata:
  name: bmed-user-service
  labels:
    app: bmed-user
spec:
  selector:
    app: bmed-user

  ports:
    - port: 8081
      targetPort: 8081

  type: LoadBalancer
